api:
  repository: rafaelvmasc/lanchonete-api
  tag: 1.0.0
  pullPolicy: IfNotPresent

hello:
  repository: hello-world
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  image: postgres:15
  username: postgres
  password: postgres
  database: lanchonete

service:
  type: LoadBalancer
  port: 3000

resources: {}

nodeEnv:
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: lanchonete
  DB_HOST: postgres
  DB_PORT: 5432
  PORT: 3000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
