api:
  repository: rafaelvmasc/lanchonete-api
  tag: 5.0.0
  pullPolicy: IfNotPresent
  domain: yeee.app
  subdomain: lanchonete

service:
  type: ClusterIP
  port: 3000

nodeEnv:
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: lanchonete
  DB_HOST: postgres
  DB_PORT: 5432
  PORT: 3000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
